services:
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"    
    restart: always
    environment:
      POSTGRES_PASSWORD: "mdp"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
  volatile:
    image: redis:7.4.0
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - cache:/data
  web:
    build:
      context: .
    restart: always
    ports:
    - "5173:5173"
    environment:
      POSTGRES: "postgres://service:mdp2@127.0.0.1:5432/postgres"
      SECRET: "chiffrement"
      REDIS: "redis://localhost:6379"
      TLS_KEY: "./keys/server-key.pem"
      TLS_CERT: "./keys/server-cert.pem"
    volumes:
      - ./.keys:/app/keys
volumes:
  cache:
    driver: local